apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generalized
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeden/kubeden.git
    targetRevision: main
    path: k8s-cluster-configuration/applications/generalized/base
  destination:
    server: https://kubernetes.default.svc
    namespace: generalized
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
