apiVersion: apps/v1
kind: Deployment
metadata:
  name: md
  labels:
    app: md
spec:
  replicas: 1
  selector:
    matchLabels:
      app: md
  template:
    metadata:
      labels:
        app: md
      annotations:
        txtwrite.k6nis.dev/image-sha: "757b685c357bb83a20bb657c104982c037ca6ad7"
    spec:
      containers:
      - name: md
        image: registry.k6nis.dev/txtwrite/neon:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4173
