apiVersion: apps/v1
kind: Deployment
metadata:
  name: md
  labels:
    app: md
spec:
  replicas: 1
  selector:
    matchLabels:
      app: md
  template:
    metadata:
      labels:
        app: md
      annotations:
        txtwrite.k6nis.dev/image-sha: "4f2f0bded06d7e08e9ed205c43ea17ff00393a36"
    spec:
      containers:
      - name: md
        image: registry.k6nis.dev/txtwrite/neon:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4173
