apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    webhook.github.secret: "__SEALED_WEBHOOK_GITHUB_SECRET__"
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
    type: Opaque
