apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  argocd.argoproj.io/instance: kubeden-apps

resources:
  # - a2w/application.yml
  - excalidraw/application.yml
  - notate/application.yml
  - txtwrite/application.yml
  - baldcheck/application.yml
