apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  argocd.argoproj.io/instance: kubeden-cluster-apps

resources:
  - traefik/application.yml
  - cert-manager/application.yml
  - sealed-secrets/application.yml
  - external-dns/application.yaml
  - hcloud-ccm/application.yml
  - zot/application.yml
  - kyverno/application.yml
  - velero/application.yml
  - a2w-lucas/application.yml
  - a2w-codex-terraform/application.yml
