apiVersion: apps/v1
kind: Deployment
metadata:
  name: innkeeper-landing
  namespace: innkeeper
  labels:
    app: innkeeper-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innkeeper-landing
  template:
    metadata:
      labels:
        app: innkeeper-landing
    spec:
      containers:
        - name: nginx
          image: registry.k6nis.dev/a2w/innkeeper-landing:ecd13d7
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
      imagePullSecrets:
        - name: registry-credentials
