apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-s3-credentials
  namespace: container-registry
spec:
  encryptedData:
    accessKey: AgCYqWRgFzKbJfYUkTnhww2XFC9iOEMEp4iaKZ6fyOMayUhiz6PnQfUwxoAmukMyrjxjLEdvM2SNsRJGHJKHazBuOG729UFwANjlhYXhdprRWyam878lSzNjrwcwcNRT5F5J/+yPaGB7+rRsiwzGHE/tEq3rEzcy7R/08X470+afvqX59XlO15wnHgeN9Gn83K5lBvEvCOLz4fJiefJMVMaiYsz4Ks8PtMffNu/+jQ3dU8KcQr/3KRPGYkHxTFZd6IxlJvCghqTuZ0N5cJUpDZvLdxPDOTLKjhv4DDYk6piihDpbPjxx+tfaBdlLhGQ1aVeaIpL+dm9u1i5Zc7+dVWPyd6fAkx85oHnSdJZJHjqJL0cRIEZfUZHYnp+rMItc/U9d+R1owA8xcKrcjYAiqE1iuvA0oeD/O8NmOe8SfwpQFqDkZcwFphxG/maoFZZOoH8g4arrzW1tVAWMV+m9L+UJ6cM5cPAQtgrAE5SJRGu6+DQrzTvUyCTmvmsgeK+orbrBlAdrFlXo8z/+7VXTHLy3mlcKa0LdcSNYnWQzVt5mvtI5nEi/nXAqaIN8lcX8R22WA81r0zCtb2lBzFrupurR/Ecp+SLgtlvMvVDnB2wlVsfuiYpSM5SzlMJhm/uI0S9ZYunoAbTDwRV01gQk7l7v+czUGK6dObC03Gehrg5xnCAhkx19qLPgXW1ftRnO3Cd4ofMtJAU/LXogxi+Vek0UrGtgtw==
    secretKey: AgBty6yB3hjhPXghxNCWPa5bgHvQ5ZQduyvjorbx5Qe6nS/dVnlNlR8Uln7c5j+rNeBYF1ggE+X02s7BIWhWhtnh0qVdMAbHSK4v6mkrir+vnNXzRBQocIOQProjGyayWF0YCDIC/ZHG61BnLzleo0TYBfqLsQYlyOKvMydF1B9fDvd/44dPgYSlvAsQ/vQhWTE3g1/87ZhDh8eSvG+FxGbw270SEMBn1mpGJQC46C6QnbUsBZELfD4OIQ0IweRtpl6a9Ob+KR8hf//KolCFit9tY27A7GQ5hrgwIYOatHJ7RJOvmKVb44WM6HeQCNx6vSM8oRbP48qbsYQcza4SKwF5gEQpkgZpr7avJPN/r9/kW3Sw95SZZpyw16wSTJ1qN490H2WiVWLBwj0N1SZA5gylMSS9N2rRdmhTrtB/8IU45mL3B4A9W5GJkhXDcKARrV4Q8re/GOAjyycrujODmPQZwBd2zYnQNoueJVHuMOxVJUkdyRf7XE+r7dcs7LEWKhXmNtMGKgp8GNvn+zm++V+a+gDSIap8LidG85j4AcEmP4WK2AjAYJIfcjz3lSeqjsxB1gyidDDWxyxPVOdi/pQyMsm9zvxNhQbh2tOQ08YwzjTVX7HZHFKfQK6bz3CiVcCtdRRotwZwTlqSYj7MrUk6HZ3PMrs2WZxLmu6bKbWbaQowbQYfnRtveteBOoEoWaXAA/RWvn5TjSV8ZoYAMx9cy1WknqUXwIzXK3qW6SNZl6OaUJGLYZrD
  template:
    metadata:
      name: registry-s3-credentials
      namespace: container-registry
    type: Opaque
