apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-s3-credentials
  namespace: zot
spec:
  encryptedData:
    accessKey: AgCbUck3pT2Di7ZWgIvry40WnxoW37r+3XSH7JdO9VlkWogx6eF4ZpoivXP8Iqk6HBDXBIM6gGnJMBBKq/769n2o+TnrkjVJUpUcxPGha6NyQP0bxSuQXpfh7ojFjZul5HAOcdgxTeelOgH1I7uCDSf6X2bqiUEkm9jzLhbV2kFy5E0mP9ws+ZhTpEO6FflEucdfYs6gp73Riei+H0IyVmWG8p6VrvjK10KSt6uKL9wKJQv7GU6CkgHTpSM7g2KF0czlt3js0Nyr34t+PNxSWKcaKg+pqM2vz9uO+dan0Z2CsWXJrX6fVOyl4OdC/qJt5W6wxgoBKol4DTWL9XNFWgKdmmRiVS1Na3j5o0XwbCjHBD2UB5C5DpVZkywlkX9c3xEAZ6w4Zt/KZPUHpcZtdz7ZKom6bIBnSfRvKtCgAhQvQKamW7rGS1qd+ERixY7ZLaFu48SGOGXyEbSzeF6nCBvzJ3UZCX7hHL32gTUY329VrlQz/cWmQdpChYQTbK6tWNMZ2WIvOZx6zfhIwW20aBmEtjaZHWblDZMvLXOB2Wqjmif2OEdHn9b3EhUbCwxOpZfuvMvOTaw20OyzU6d4JodZO+Ug/pX5ALltx7fSkHtgGCApj2qrrrHRwdEQaWz9PQ+KzzxRSLfD/S8IbeSAIn4113zbc+cqfYR5iFVkIGXHRlr17+1S4G3ulokHgez+6XJlUGhY2xw7QYwhbjgOOVYzrJKtFQ==
    secretKey: AgAFfj5GddKuHBXhwEugdkyAtFTKb5xVKLw64NBp7XPXibKnWzBou+bJKQqwEjmm4RszWk3A/uV/NKFlfWiwI+CNtMegE9sIpZkx/GaiU4kf8uO3A7957inHFCjbpC8dpsoPXkPoxKs+Rot8d3TrTwiekgi9F++zoB96IhGdKXPoZ5L3kZdzvmgYnw1nFECW3Mqex16RN08fhxx2lvdkC4x4r5tcFHmPH8JcWJI/7L9pFBjMkOTLayuq98jKGqE5qEBi21lccflKJbtiTgOo14lnbnqrp1kZQg9rkhhx3/3VMEDXC/gxgrezvx8XodLPZG/TLfuICTaGV8rk1XAE34lzpgLlJaFQDGkoOa61YYtTTqinYzqy/g0v0YMak0qtw38zoBedlea73iVE3snVhV+eXhN953prR4Y47GViq8lB9rlIt1Ah0mYCrLH/f1scLY5DC+vugI/GBjFUAvfE/kqxJE7b3sowx3B9I99wydNcp/oOwwXAVF3lJncUcy1CQ7UxUjgYeVUZnLS2IEAxnyCwY+hrJNongydfGGoeEqBgkkxjwLdexCxkyK2UE00z9oBZKW5zRA0THM0H/3Ae1xNIgeLw85iCLNcxeP5VeaJe/k4sxg2pNdzd5nkF7FUVDEORzQ8kb0ogwJ5bM7ogMU0H8snGKgCGilWOQ+URgF1VzXbn5sxDeHc9ZqMI6gOgE0zNnQx0ypwk3j1Lbo7ddgcp8K+Dw7J+7W7QD6VcUhSwbNt8D0ynnUm0
  template:
    metadata:
      name: registry-s3-credentials
      namespace: zot
    type: Opaque
