apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeden/kubeden.git
    targetRevision: main
    path: k8s-cluster-configuration/platform/core/external-dns/base
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
