---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: innkeeper-relay-secrets
  namespace: innkeeper-relay
spec:
  encryptedData:
    UPSTASH_REDIS_REST_TOKEN: AgBF49xANuKPyNANVE/rV6w1Ay0SdtGpV8EH1m5vOW87OLoPGXHeAuyZ1lFFEom3Z2bxEH6e81+lHXeP02dEcLXRUMv7iJbDC60YldIjYDBBJY3YBqP54pcySmT3obGg39l6t9eRnUhljtsZLBwleW/Wlt5SJ9jZ5AFaNnHn97Ou10j14pFDSFm9eKWudATfqmC7D+UcUQpafsA0mtLytXRVvW9O+fxK1t0JJI7sQ5szakRAnNvFkRbq0z7ftRynWBwRr5XZRivTqRmSTkB3SQlTyGxQXfII6ooKR7N+Oxl/QiEI1DEz35YC7klisckFIiFXeydVp3uLxjAHT03zkabGEReEnoOmLi6V2weRlw56b34wmyjPtH6WtAlC6Sbdf1AnmS+p/zdIg2QzOxmQmLfOZdxfcpKbT4EDhxPmmtW+XU5HlcTlRmVY+nMXpV/yh7jeHGcjtjHilEFaDrnzAJRc16NpTKuRWDy//fFt5K2quA0fglkmLqZlvh58TMiIbwazl/iEjM33xC+2BTtcoAR5UKAcUvwmKDzqGHaMf1/7b46bzLTc78ybbDyi6i5pQHhk0KzNyI7iP/gCNioy3LJg//EwZZ3F63h4aQjBGMwIMtzeq3GnKurXQB5rJnSnmphm22JrsbpyVePUH2E1TM1JvxNqdxJhwGLbn+ktYx9Yv/EvpTgIJCIpyhs/7BeRsTt2EsKe7IXheCYOVJzoPXefFkHZ/nTd1lrzZU841ZcQcvpsaYcqb282oESqqMiaPmgUTcnzzCxpZtjoTWPoPg==
    UPSTASH_REDIS_REST_URL: AgAzjjzQBbgqh9lEDYbiMtk5VdjKgHLZOzCkIczt7O72X3QBLxU8aSLeXqyMuLlyk2dMOPYz9S69iPNR48wFGglDdwfeI4lklrQHcwJ3a6zk8n5UOuRAg5QCu8pLCpmg2s54wehipS2VjsTsM6GaOVOy5kFbGtGBd7SINmCdlWPRkO93eqtaE916Xfeq+YXbQZwqotjKsWmZQ+5hIk6kyFZD4CPsf2/tP7lWErjdC0m3LEnZqY1iNR4/OWwd0OQAp2tVLJWM8ikIg7lxRjWStYUu+Qwe7kFGAvG/HNwh549KmLfac4++kvZJz0l/uNhNokvEKDToWFTR+vR2AqX9GMr8PbeBQTf0M18MuijyJVbXDDuEI/Lz8GDdYUpZnabbd2VRXVCRk/wZ21hIvqqKncjhMCIPvptC0ftCdPzEBCSORTcenwYRgz27KOht4qYOeEMshngsSTToVkBxhQFF/ONZqyCKbm5FwjnfArbIIH31MCnFSEYdUcakPh3/iqw+70QGEFQce7f3ab86Dfqrg/SVQ8G7UdIk5lITw26w8Is4p4tPho6W3BemttjNlUpbWBlA+H1lXEiHVW7tdmvMDB00mfJMps+xmtCrscsaIuBz9aUGjRFGzQBnDF8HoXlU+S4gvMw7R4gBAgMmf6OHyCSA9cO6p+Fv+uu20wycwxRzrJ/Z59iva4EhguRmJcci39SCMtNv2jVdD86lA3F0keORfPf/AqTo/XfDpGSs9EGBsIWT+IPi99f6cg==
  template:
    metadata:
      creationTimestamp: null
      name: innkeeper-relay-secrets
      namespace: innkeeper-relay
