apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a2w-code
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeden/kubeden.git
    targetRevision: main
    path: k8s-cluster-configuration/platform/core/a2w-code/configs
  destination:
    server: https://kubernetes.default.svc
    namespace: a2w-codex-terraform
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
