apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-ccm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeden/kubeden.git
    targetRevision: main
    path: k8s-cluster-configuration/platform/core/hcloud-ccm/base
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
