---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgATGyXoCzq34r6M4mCHV3xY8HgpKXE8y0RVG4FhK5DwfhsEWcFTy0Xaw2vR9G4e81oCFDMLzcF8uCdd8rfZheo9k4RowvZ3vgnRpYhlrUpKMM+XV/R5o/zVQJMIW0LwLhf3TKwL4WhQqIrk7ibM/VcyA0MXUfz4pNsKxSM4HTpQL8uwKJVS7vQGy7lCNw1yxs7//CTbG5x83HIo6qeATRmkd81kt1wCI7U03OwQMVMY9sT917b+ZJTWXpRl/emcs3ekhVr4biKmnW29bgu1gCpsbauUu1c5zO3RpShQlV2tdWlyaa04pwG/5GFSHdbxqh5tW2+2XASi5EwEswGtbTVKTdIj1dzJuDZP0FPmJCoGfBCrMRp20eSSQyKYiQgMGJFq6wLZC2q56fShTay9T5GbNLtZsOT2mdOANkW2vstScXGxy1jIVQmbuY2DR1nVlrUYKfjOFunOtxCkwNnjUt/vgofu17nr38aPAapLHrL3Y3nIH0te1g5i3/psCqbRHhUT3KT1JE9/s64ZU4MKtlC4lvPxCFgDxLPKzIpPzQvooDDM8WyCHHwfjrvIALHNtF2ICB7uGLZEAXTcJF4K/fPdDoy0EoRwK4tXcIdzZ3nUqf+CCUciog8gGDfyhrAFbStDSROClMoAUpugP4nywmazYs4VGahR8WnWAZYBhEb9GIdhV3IauqXbo2Xr4y9Q6tAMYxvM1KgQRNp5tanO94zNpIZzQvhh5aikIOpTZ7zES28RGJPqzqvq
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
