crds:
  enabled: true

replicaCount: 1

resources:
  requests:
    cpu: 10m
    memory: 32Mi

webhook:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

cainjector:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

startupapicheck:
  enabled: true
