---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: a2w-trials-secrets
  namespace: a2w-trials
spec:
  encryptedData:
    arbiter-key: AgBc2Xy3masLquH0q/Iyw0jvPnFIn/4r9MuzpfbvQKPSnq/da8fAj+ABo9YRWEl5oWo2ZSYAFrRa2oriRGYI9M+uz3azoo1sruebHkFsNEoLfLnU5ugBWmaFVyo6Gu81BfhTRSECv/pHXhwqRfdp71StzCyBoLJzgm/+CbWmKsEszuGo6oPSF8wpFZMwNf8wgrZjSegmJRwi9DM2qbRRG9AhVM1e4zKjszPpZrNgbE0vUjyY/u4nbIWAEjwo926LF/j+H3tUMfOifcZiouJLO8cz4NTuJ68DJ76iXFgEdXy5wr/eP6O2ldrTZx5vjiyEOp7MkDYBxlsTX+AEsTYvttMVAYt22hwwids3MZ0yHjIn+vOhQ2BL882ZGtpwhM36+Qxf342O4nLaEhLtNNFUl1x3FzQALv93rVvkB9a3k/5Q8uMH2B+w77u4ul9Z0hSKieMzy4dycmk3VKXKlEVGiOu6j+dERAOcbZTlD5hziJqdxHfxdRCI+tzu+zlgn3zC4qALIcSEAGjZ3irO0SiwA0r9H693RD8M9ht1zQcBzPfwdqwmBsopLrZGqA3IJCzTyvCGU7AvkKVaR4A3erYu2TD6R6SLj0bot6PN6Oub4x91GTVqhvhFrBn+t+PJjPomZwgNSOohxg0pDq0oU8gkkkKeGrkM0W0h1cF+i1n5xNHMfFx7YBJv/x6uTi6DOWmh959fvYEE5ymjBt/ZyubkGG0kt28/Gycs4cclikePB05WIROTFGbwAZplt3+goiw/Xv7fHCKZy1/GoZ/BqhmsTbJC
  template:
    metadata:
      creationTimestamp: null
      name: a2w-trials-secrets
      namespace: a2w-trials
