apiVersion: apps/v1
kind: Deployment
metadata:
  name: baldcheck
  namespace: baldcheck
  labels:
    app: baldcheck
spec:
  replicas: 2
  selector:
    matchLabels:
      app: baldcheck
  template:
    metadata:
      labels:
        app: baldcheck
    spec:
      containers:
      - name: baldcheck
        image: registry.k6nis.dev/baldcheck/webapp:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: baldcheck-config
        - secretRef:
            name: baldcheck-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
