apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - gateway.yml
  - database/pvc.yml
  - database/statefulset.yml
  - database/service.yml
  - database/networkpolicy.yml
