apiVersion: v1
kind: Service
metadata:
  name: darling-internals-service
  namespace: darling-internals
spec:
  selector:
    app: darling-internals
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
