apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 12.0.0             # app version v1.17.1
    releaseName: velero
    namespace: velero
    includeCRDs: true
    valuesFile: values.yml

resources:
  - hetzner-credentials-sealed.yml
