apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: a2w-codex-terraform-tls
  namespace: a2w-codex-terraform
spec:
  secretName: a2w-codex-terraform-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - a2w-code.k6nis.dev
