apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: a2w-codex-terraform-data
  namespace: a2w-codex-terraform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: a2w-codex-terraform-codex
  namespace: a2w-codex-terraform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
