apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-pr-11
  labels:
    app: md-pr-11
    app.kubernetes.io/name: md
    app.kubernetes.io/instance: md-pr-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: md-pr-11
  template:
    metadata:
      labels:
        app: md-pr-11
        app.kubernetes.io/name: md
        app.kubernetes.io/instance: md-pr-11
    spec:
      containers:
        - name: md
          image: registry.k6nis.dev/txtwrite/neon:pr-11-8cbe08a
          imagePullPolicy: Always
          ports:
            - containerPort: 4173
