apiVersion: v1
kind: Service
metadata:
  name: md-pr-11-service
  labels:
    app: md-pr-11
    app.kubernetes.io/name: md
    app.kubernetes.io/instance: md-pr-11
spec:
  selector:
    app: md-pr-11
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4173
