---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: excalidraw-tls
  namespace: excalidraw
spec:
  secretName: excalidraw-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - excalidraw.kubeden.io
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: excalidraw-gateway
  namespace: excalidraw
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "excalidraw.kubeden.io"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  gatewayClassName: traefik
  listeners:
    - name: https
      protocol: HTTPS
      port: 8443
      hostname: excalidraw.kubeden.io
      tls:
        mode: Terminate
        certificateRefs:
          - name: excalidraw-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: excalidraw
  namespace: excalidraw
spec:
  parentRefs:
    - name: excalidraw-gateway
      namespace: excalidraw
  hostnames:
    - excalidraw.kubeden.io
  rules:
    - backendRefs:
        - name: excalidraw
          port: 80
