---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCi3O9MQbhlejkgeQ9qeHzxIgXHkSBM+UhYx2Wwmujojh7X17BmRVPJBJufX1SC/9HneDxjJ9avWYAZHI6pYR+rjis95UJimT30EIxUrJZMrIv+Aqw273pHR/OTHnTiohCoJcplR340BaZIB04WTxNOx1fVI0O97ICCKQ8lqKrApG9DOWZr4W89Mcjfec+8h1FiHB9FRcR2Dq+0rU0hyG0gVkMWl6uCZ2qK85KbS4QMuKFLdf7uPbZiQfXvVE7vJG9y/jcUWXWYmPqFt12kxjdcxd/UMwuv9LbRpSxpt/quXFumgF21FxXKWiZALxeK0vgh49RHwtXKNRUTLCE03wBfFxRapbAR5tlCKv7IYQjHo43FZpHpYh5m80E2fgzghS1SAy0zdwuyr+wkkn7H1NEuIbDn/FB210yd2a8FJgIKwyBBO1+tSleWPXkSNyhp6CQcbNbPemmMaNJWVuj0VYgL0+Ot7MnbA3gu/DiW/DPRipQdVI3b8k7OafU+QEZz+EewCt+3AbV9GFuC2SUQIS6PxuE40VBF71gMFc3TbBagnE239R1teSfXlXkdjQwm8orkaaigjaDhSOU+ydul45PTRGYx7oe4DZe3IHxCuXfhHnDye5WDvwoZaSmE6A2z1QggebvYdm20jfZKwtsu96h3cCfllJozS0SgHJVsHkKr3UyxLNuk5nf1pVcicvmEwY7my9oJZldwTvI2aLCE3z9D+5AHi6QQunF/zYJeJ6TEn71TRsRbZDsO
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
