apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgA61WR1CQH2Dt5Sq1kOlOsOBnak1dRMr1QNFZhr7+p7iML6zY9smnWOBLfLSyBbvkA9Y5G2NyiH65mOsY7Oa7TtV/R/sMmzGgKBOOJDeZp5FhRU/h7zShkYwiKLq4LcdmMN1eKk6z6Bk7F6YIXY1nOfkYPQEL43ffx9FolkmgVsYn3aJns7as1pnQryh+BrUZriemP6E8to+by14aSujI+nAuoQw76pdfUi4F1+OI6kPI9mY64HIy0DuqoFFJBnEkyuXhFZgTPjiRUINYPQmSgjkNjZm82hZG0x6NQut8wr4Al1TzRGHXvOrHlkJSnqiH4UPiNKpgmc5HCkSeL6FisGGMuvc049JUgJRZ+pHGSmCUOLgl0GcSjqFTGhmZ1rfKdPcSuj5vtPVoJ0q2iZPEp4rAnhVj6mzus4TvNOWPeLS8M/dghWP/Y4mnammbJKc4+662/171z1qUD6WHNEJ7z04N4CFwmKNoAT43oDkVxZB9HMCqzXUN3lP5jz0JVIuQR0XDe1TUyEexHTkfSERBNMDXg8eVSeoGFhxgC+t3MekHQjMrJbuBX4zpRyvy+hxsGKEhwmUHZb+liNGfWtlndpVHDlZCF2d6sQaNdk/Slbt5VyJgwyMpPRGJ2U/SeOw1VdmfsUc3uouID0/c2ia0m5UweWLOyahHeMU1Gn6/TGAjpBKqya8MhvlW7GZWP9x/HsYOkjgtSi66kdfD7ekljmxPB7x4+ZpzifDazn70l1XbZwfrSFvte6
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
