apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.16.1
    releaseName: external-dns
    namespace: external-dns
    valuesFile: values.yml

resources:
  - configs/cloudflare-sealed.yaml
