apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 3.7.1
    releaseName: kyverno
    namespace: kyverno
    includeCRDs: true
    valuesFile: values.yml

resources:
  - rbac.yml
  - policies.yml
  - registry-credentials-sealed.yml
