---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: kyverno
spec:
  encryptedData:
    .dockerconfigjson: AgBfcWxELb0QX2qdRPZH5DFDwmXMsjQOlBu9HPhVKnOJbcH2lqR6bH2UNavAvwmFMiQYHcOTCeQBO8W5YJzhqw/FRke12Yc5m2tJ3CZfE5rskrvM5rG+z2Dt1OSRonXYo8T+pcfK5NeLtJVGFIjOPhWX/v2D4+SbHxLfxO3BjcV3tPB0Gyhmpvi4AGhGr/A1AnadCTNzhGXAPaPNrgpA8PLIrd3wYgfjtn9WXXNRFu7kso5sgacAFVKuT/gnn7KLHaKPTognH/fDgs4QyPy4u/Cw3soyJUuCv6UiODlilc2fgSOQcXir+pcp6LzmNaK5v1hzo5QRyD/WMqu4HVk/z0VdDxisemXuobOsw1vXHdVGqa3meyD7KzZcZDjjjxLF5OuY85YOBqlFV9K3hdRNu16CZ64OIPEuV9mDgRU9HcikFwZ+ospqnF7+seELyU/rP8UwqvN5NcUueH5Vm/6cwziYCYh/oczS3YLlmMTsLPXycRa3Vuje8RsWP1zyYvWktvi925Kv00GVOKWJmet6Xd6Xm6UL9dshNy21Bt/PHax7b57OM16nRKcHBhz8Iu1CACMd66mofZsTC4c7NptAsrTQDNJjYKCA6keydVI2CyYR0HAxzILK8sX4KRac2cG3oW3Z4p+qaY4Zoi3Z3DGoA/djiRAsDYe18owF96ei4G+3vOzZQ9k7/HkR5OV1wONFmDGCP1f4+GYZbMM7h8DVQ3Ngt5nMf7365vdigJJ92Qb5EU2wRVXWKAEMu5jHMuTtpLopx/Dd0C0PEzaXoofyt8YfTjbNvhCT8LvJMvwPE6UkpdgjMGiq9kxsHDQqeTUmv2xVbCoh/XjdTzUz6oS8spf5QAzZ96RR1tKYcv5d5gWMtfp9ghoYCsFQXyVuVahQLWJ0E/LUAEUPE3zDJHyCZgl8LLKmxUIOyAmXXZlZtgcuy2GuahSH4RUWZ1mA3Zpq
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: kyverno
    type: kubernetes.io/dockerconfigjson
