apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeden/kubeden.git
    targetRevision: main
    path: k8s-cluster-configuration/platform/core/container-registry/base
  destination:
    server: https://kubernetes.default.svc
    namespace: container-registry
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
