deployment:
  replicas: 1

service:
  annotations:
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/name: kubeden-traefik

ingressClass:
  enabled: false

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
  websecure:
    tls:
      enabled: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi

logs:
  general:
    level: INFO
