apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: migration-test-charlie-apps
  namespace: argocd
  labels:
    kubeden.io/experiment: argo-migration
spec:
  project: default
  source:
    repoURL: https://github.com/kubeden/kubeden.git
    targetRevision: main
    path: k8s-cluster-configuration/migration-test-v2/charlie
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
