apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-pr-9
  labels:
    app: md-pr-9
    app.kubernetes.io/name: md
    app.kubernetes.io/instance: md-pr-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: md-pr-9
  template:
    metadata:
      labels:
        app: md-pr-9
        app.kubernetes.io/name: md
        app.kubernetes.io/instance: md-pr-9
    spec:
      containers:
        - name: md
          image: registry.k6nis.dev/txtwrite/neon:pr-9-58b31a3
          imagePullPolicy: Always
          ports:
            - containerPort: 4173
