---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgAHhkF9KfH0kEcc51BHYEv1hCswKbkldquT695jVDDyjViRPxDtjyFMQetd95okcuUytTPSliD2w43hJSmAOosntnSM3i8q8wmBQA70Nzb9Sm2oaK/BwY8uTjAQTEDnmxocqjlTivL+CjVhFKiQRt5UWzumdqxdP4cm5/jUUfU568D9QppgOu3UkwYKrjrIG20k5J5bd0tJVmO9ttOAnPj9R6SI/l8Ecnagk2d7NbHAu5DRvhyzyzqd+1oEyHctVjnrJit8+JCqA9MHZ33ygqHfjtjiMcquGXNS2F2tDljYHATQ0XU14QHE42PTMqDAsLIB29fyPCKWPoSNwnrgf7F3u1xtPQKQSAe8t7Udo+B0LNms6D3fbsaxTsViHMhdV8bRwGiGOaQ+8p0H+mr0uFB5t15YtOOnDKGzhE3TeUdhbN5eZHWLmcwyaDFy4txz4wGRZpRM3P82z++wtJ5MB7CXhzp2ZvgQFSZ/VViBHHwZL+aGC8u+fCBT2IgKBnBGEd803mYKifsqPzP2ZhM3KUP8IVLxoWCToAqNfLJGC63qLmWZmBY6sKB1VBgoPfQHZdqola1Cxwx9drKfclN0ICk53bmrEe42EKjuB3z1H9phwLaFm56zqG3UitcuB/9xfUFxr1c8FqbXCbM8IDVf5l4keIdlRcVrThoV06jazIM6bOPGqy/t2cgzaNqG0DIuD9Dr1PdTbhIXHZA+lxodraURO+x2GjfHcbEqQPsracdeRBYkclbppN2cWVfSwTj4XBVPEMh2cOSUs48Z2FTiqoLI
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
