configs:
  cm:
    exec.enabled: true
    kustomize.buildOptions: "--enable-helm"
  params:
    server.insecure: true
  secret:
    annotations:
      sealedsecrets.bitnami.com/patch: "true"

applicationSet:
  enabled: true

server:
  service:
    type: ClusterIP
  ingress:
    enabled: false
