apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vui
    repo: https://seriohub.github.io/velero-helm
    version: 1.0.6
    releaseName: vui
    namespace: velero-ui
    includeCRDs: false
    valuesFile: values.yml
