apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: darling-internals-db-pvc
  namespace: darling-internals
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
