apiVersion: v1
kind: Service
metadata:
  name: md-pr-6-service
  labels:
    app: md-pr-6
    app.kubernetes.io/name: md
    app.kubernetes.io/instance: md-pr-6
spec:
  selector:
    app: md-pr-6
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4173
