---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: boardchan
spec:
  encryptedData:
    mongodb-uri: AgBEmw6tB/dHv0hTY0r8CIn/ocq6tSvfOamqzOvkUBexyIN1R/iwWkYKLVh3xwmC843sDYq+IHAycLKfLN89UcJcbvaH6PsMHV9VJ6qO0n2Y9aC0ATGsSrNxt3gluOmPw5KEEiUtbycGUrlo3PvOW08va5Dnyq8f5pRPQywutzUWtwO8dvBwsHfCYPO3wBoWCyZphYScr3cbeb8RjJk4+SSBeeKtwMVZJ2mBSguAkL7f97oFIa34WvV24o1HCkorOky2LAWHEt8pBP7jwcBSvZPAocKQnBs8Tei2O4KiSHhYmYnYamE/6zSjQA1FsDz91wtk7lpUxtoEplm4r2YNhV9mlniUNrBwe1tduQz7jLg0aF6vE7gG6axriaojxcK0JiXsR+SeHuWDV35mE7Nrz6fNW2IHY/aEaKjgBQ7++l9XAgO+IrQs/o2KRo4THGrNeTBQ39zStEDhe6WKqFg1ddyvFRMmY52TmjMK9MDFE3EUQV/jaTH/6ckLxLpFlrm2FCFJ8bJUJEfVS8TQabQOxaTzUeAUoUe6lDqDH270c25S1FSN10rDEsNEjZSQfctjV4eosWRjS+PRSm4+6eiK9TDNE6jU4zPGGrRZO+NCGl+DcjxxD+xtCJg9cOrhDTQIi/9RgBfeaRB+Sr7eFBK9XL+VvVrBh9M2LeRR1h0T4UtfK/8rUEELpz7aCp1RjhAJxeg1nCXeDTuVt5ef0xq4rk+GYBsADhq1jWD5SDnARtV2XR6nlexKwscwrn5J2bc=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: boardchan
    type: Opaque
