---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reminders-cron-secret
  namespace: notate
spec:
  encryptedData:
    secret: AgAp3xS6p+R45NGDdH+mIAS3ebTPnQ+c7KYDfj+j5iXvYtUqmrAxjJeUqITp3mkXuXQXoeOlA9c1D3jSvt2Zvd0vz8/TJZc+Q+hq0c4LdbeUbY4ESe9wmsxlXkoExXJQiRpIj73HPNotlYnHL+Y0IfuvofT+JhNR2OVKu2I+PBPaAf5JXLBQFLEpaeWDhLM3vpgsgLGCTm6++CmCkKwn2Y5qXKks+8dmfe/8Xpk4gTv2YQPvitlDQHd2/LaexxomtQBfLvfmSyXpyjSjwE3WpoF3/YI28EFswJ8k1WER4hc8CieK8lWchKleVruvEBodWAC6fe3+A0IKVZDgK1RpGEKRavsvDVdE89pQ5gU3Xgr+grSsI2mTr8yyoQXuV6YCKYPfWJ9ff+lUvyi9bXCKf4krAR9l8+5DzGxSAkEtfOeXWpWYmt30zJnjG14ZX9iydmXZJ8q00iCoVlYhjHa8D2s96oDwQJLXBgS1M5HdG/qb7lg/T9TxEXkSpBDNURcvHr5KzsfYarQiVkAeFPqpdsJhSl0Wjh/9d2qKdSEPQ2AA+OybLw5mldiX75ojtojifbRqgztCyzLxXessL6sP31D+Q9Voel8+Iu7g2ler3feTbpA6OPUbFs0XHtH8rmWzAd6tsWli+PTlfkTmsHpyM6edvb+arZDKp6+U5GwsIZh+VQmhxm+D24OFL1ANnWkhMrldTsZhccWLR0H9L+eeayr9USgWmdwhtR1sJOkxTh82F7C0jg==
  template:
    metadata:
      creationTimestamp: null
      name: reminders-cron-secret
      namespace: notate
