---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reminders-cron-secret
  namespace: notate
spec:
  encryptedData:
    secret: AgBpAkY98a0a7OaN7dIUqVHR9leFWTbwqZNstws2Bh6s7+P46bnPOM3nimaaggJB0yQUxtpM4r6chxpFQuU3WwoI3mDm7iGCH+C6Q3QnCKNtfPVksLLp8tKgngfUyQSVLssbWYf55sEjJixAsBwlkbXs9NBcszCw3qLkiCaW2Ahc/tYy5Vd3eyVeN4FDOWO9Gof9V80RvRimFj7eKJQKW5eD/VtdvLCKm8oL2GyEtX4j2O7TgHgpv2qCC+UZU+CKK800wXYDezUAO/bvFWFRIt/OeMsAsGHjXTq9d3vuqTQAtlyqL/Jhy5+DnnpfPraVGsKEmiP/xD2QguyMdf1MJ0s2uRcQhv5H8VmSOutw6kwAvAMx9sf5IPMtdF3O04EFYN/4rDglDNsrDgyXkpD/8iC0nTjWQjisky2UbEkoJq1VtBz6p4n0tpsAYEl5Zu+KF0wuKFllqV6Z7BT0bCyCFALuf0ZvGlmalWxSeLmc0AMlu+GDcvE87G1hKutF8pRxIyA76gA70LYQrVP86bXehSAjTXGM/GrgcG1An1JaOzebJeT+ovkZI6hfSQk73muqazYnZC6y2HVknd2abTjjgMILhxh6V2qSVo33kYPUjYqJfQAIuIc036MkeAkzLjb7oaNpMIWIUx35b+DzQKVt1aFMBrn6/FNTFDlniprHK9eGohrjUVUo1Q0iCGW7Z0AgAnMSqWWtIIBGVWu/9OwYpNhKbvIL8yDz8kR58lSY21lWBBftAQ==
  template:
    metadata:
      creationTimestamp: null
      name: reminders-cron-secret
      namespace: notate
