---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reminders-cron-secret
  namespace: notate
spec:
  encryptedData:
    secret: AgBrvem8fiO3Gi9CuKt+sb46Oep4gVaYCIW7hwukdl+K5L+AOj4pHbA5dBkBsWCEWRltaPhrB6xL3s4KrwzYj/50r7YiUtAoZJHWdZ94uQJQpTDXz4rLKRBHAK2GAV5tOLo0RH+GezkvQrdJYKufj+aBtf9cgb5+dF0xXF/S+ds6D8n1X4mZKXxOQs0bER/YK5ZsolE893qsYVDFbv2RaVFpQ78rG5oBXGc242GqplXBDVB87FF9KCy0TuPMrd68nvhsllmyDCmhMzoOYWzR8XeidMNFZ5rcVJjzp23LosuL2UdhleFWp0kds8Y4TzYgAc6b+JFqKbdLjiq/yItl/pMQ9bt3LfBQRQTDMOOXETtKKFbKH9+v8+xwdDkhhHTtIzYSmtbewYg/Cn3UVKc10j3CX1AdZP1hpOOnE12kfSkD3UsUxpbKA95ZblG040N1oc34bfBHsDpNhQK7NKcFkdnkiy+U+eceXFCqIxMBZOWQA/2IRQ0uf7p4KdnpKqg++BXhwzTEwkK2vJGeT+yJ967EzlE1q1ztWHTFbgaAWFqAne8pcrLJjSw/s+MTkClQ167WK22PDwJVMNClhKM7u0Wk+ArQB1V2XvBzq2WZRDUaD+kymmcrRziFiOTDUV5/3lLkyFKXBobm3Z+F1haMRim1ILr3TwFbXlD3Ax3slNJiR5KhvR+O/WrzBjtb/gOyvrjy9hl3NEmiHgR/+xZgDnf1a+gy3HYRYuLqZWCDLh2o9D7+zw==
  template:
    metadata:
      creationTimestamp: null
      name: reminders-cron-secret
      namespace: notate
