---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: innkeeper-secrets
  namespace: innkeeper
spec:
  encryptedData:
    INNKEEPER_SECRET: AgAEOdz56G6DJdnK3AaeqtPBxRUrguVpIY4ftgbWoZZRVFwAzwUfMkZQiHj7uY8sqxrn06DYDDAY+2aBpy2faptMRi5Cqbejp/69XTPv5QOPosH20MYKu3XgFljStI8gP5Rvx7e4TU0ZMR+5EeXmMCA/1peFbkuUdDOvDCwri1C7Z1jA4GLGl7p9pt77x7O2FbEJBcML3Z6MuMnb/oqw1UuxJYF72Sx4uzBDKxX3ptzRL3+pfKArwAYhG4Np2+Du1wtR0v+gR50W7Fw/eoimpaaEDWRjLFvZQU0XtoXnVUFIz8uE07jGlbgflUZT+Sw82AHT2J2CBnWJJ1cirXoUYwQIk5AqX15AnaZJXMNRFkvNlz/uAoGl+7OSyDE7s9zig7h5aj14BRmXe/jdMkgWQrBU8JOweoG1wyOwtGolEVV/MVBNTKeKlU8rmxVOKA9enftSqiLHcvo0naYUoqPtahY0sX8d6YZPCJ9C3YrA3FDPIphMtnevm1rCGxGC0M3dT3hZ64MsqT+v7bua88iZYLnYDCgQ6hJJDTDmV7N8ty+ol/KBDbMTR6669JI0kzGpVt2A9KK5i7EGVhkqlneR+HvDZqWzdEbgd0wMAT3F+xxTKqZ0n9c3MxbpGp5JNrO1WuP5Q53afaTF2PAFQtxZ0X1TBZxkBQJ3tYSjlyrUPvMAUxvSn3HohEPfcDdv3wWx6ZMrw7gL6+yIVHVqFh4sNEufC7evi0razVCy/ocXr8whDNPgQVH0x08vwZQ86l91NA2+8q4tKv7D3DpIQECq+bu4
  template:
    metadata:
      creationTimestamp: null
      name: innkeeper-secrets
      namespace: innkeeper
