apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    token: AgA8GS0RwtpubYNY0/Wwt+JFK6wgGWjXZHv7jICG4u9C+nZjteW4+0LrFil9HUvs9LiwF3V1/uPukRGMWZ6qRmBrykjxVUxW/w2AGUz569JXioVU6eFvZkKsRdaOWxOYCdJtwdm5OnunI2hnglN7TVxMc9SRNHcB0bX0ycKjCd5ID8e9JARWDfJPb3jXdmP+0LcgXhwOTJ4gdaNI/FWaOV/6t/8oBvaKZ2otMuiDrDnUD+ExqiYk8Lv5eXbABwL+zMFlBptZac8PQjM27GJ0SiXSlaFJClWi7fFLS9pyAlP0I5BLUFxP1NBVej492oIhM0Aftm87idMBXmUrNo4+7alRwFJN9S339DlgoHNU1UGasSVY6Ty7jLohBT3bd7XoqhdCyHXifLxNqLttAoPPuG+0XXGfetopy8gVmtj7FTd+e4aliNVer5mKsd8h4Gux0PGBpcaXrht8YlT4Ph2ws6OvgFvQelK/Gqa+lNEdlJuInaGB85zFLcLMcbV0MFtzwIwBpZmTHBOTdU5Q7jzRJvLc5MsgZ5g0ktV3FSBIVu3uX+ka+sAWA6nj299d84OtxpVL7QPT3lgPyNJkT4BrFU5qbzL6UBk9atyWfcU8ZQbvyNefqd1rx4Zv6dQZrJsbi1L9R6LPLz8ST/S7qnstFNaKSIezO5DYLtCS47K/plJUB4B0Xi6ShRHWPWyi/4IHafCHovdNGsT/Ko2LpBsiron/y3OmcGEdDE7jDz+lOmsBETNnbOlsHQeivVTgI1nScMSH77QKoODHFnQBwuO4hBpj
  template:
    metadata:
      name: hcloud
      namespace: kube-system
    type: Opaque
