apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    token: AgA8GS0RwtpubYNY0/Wwt+JFK6wgGWjXZHv7jICG4u9C+nZjteW4+0LrFil9HUvs9LiwF3V1/uPukRGMWZ6qRmBrykjxVUxW/w2AGUz569JXioVU6eFvZkKsRdaOWxOYCdJtwdm5OnunI2hnglN7TVxMc9SRNHcB0bX0ycKjCd5ID8e9JARWDfJPb3jXdmP+0LcgXhwOTJ4gdaNI/FWaOV/6t/8oBvaKZ2otMuiDrDnUD+ExqiYk8Lv5eXbABwL+zMFlBptZac8PQjM27GJ0SiXSlaFJClWi7fFLS9pyAlP0I5BLUFxP1NBVej492oIhM0Aftm87idMBXmUrNo4+7alRwFJN9S339DlgoHNU1UGasSVY6Ty7jLohBT3bd7XoqhdCyHXifLxNqLttAoPPuG+0XXGfetopy8gVmtj7FTd+e4aliNVer5mKsd8h4Gux0PGBpcaXrht8YlT4Ph2ws6OvgFvQelK/Gqa+lNEdlJuInaGB85zFLcLMcbV0MFtzwIwBpZmTHBOTdU5Q7jzRJvLc5MsgZ5g0ktV3FSBIVu3uX+ka+sAWA6nj299d84OtxpVL7QPT3lgPyNJkT4BrFU5qbzL6UBk9atyWfcU8ZQbvyNefqd1rx4Zv6dQZrJsbi1L9R6LPLz8ST/S7qnstFNaKSIezO5DYLtCS47K/plJUB4B0Xi6ShRHWPWyi/4IHafCHovdNGsT/Ko2LpBsiron/y3OmcGEdDE7jDz+lOmsBETNnbOlsHQeivVTgI1nScMSH77QKoODHFnQBwuO4hBpj
    network: AgAY+qUl4MqZtYwwZZexEV6woYToV09HcGGzE6pLugCKtbGda54fVncxSJVBY9eSKwIHoTJr3XRCQcpQSOom1KDlyVBIWoTsHdcO+b7jkKOh+SUA+WN0/0AsGoWbhceRxVUEr5ju/rYd1swDSfSRiPKqNgCxWffOONjzX2ZN8/eqx2d6CETSUpDAqpewz/gj15boY9ctEzw9J8Zbg2+CKiFHcRKxGZ/q/hcIr1qzmiXeFqXi7VlZjce5gkPilE6N2Czsmc7FSYU20y0RHXy2KJOIgmQhhPJSoPwJVwEharFSAsSix6mJ/uteKQTdbeChIb09B5gphcUq2uryP6ZSyR70XN3UoHz9p0rdThp0RyBEtuWfpn/xSb/DOVvbTMmJZI/WyLtwz30f5IpwP4tccnJx3eu579qYGYF14hQFjNwwG7XNWklemA5K0tlFtW0w6s4pSkfsJ87Q4Rlr1ubAV8hO036URwRe0Fhpn6ER3LIFrygbdv1dsjmr3FJ1WDCgU8H7GaobYBCOofBU/RYdcSLaUaizEK6fHpslkSR+JV21PrLDMY9xua5Cp1ckCr7z91H8lPtOqUQ3Ih8ygGGcF1oozlKuyxON/CoFTIkmzGR2PvoFb3pHLvGXVdGsMtXGTUhp0QE1mgEuHaFvW8qqBa/a/GuQMeBm5Cf8djB+u7ff2gHCz7q8UcUsE8uo6B6Y4t2OfEP3stjVQgpNKeOv7iBewzMhNf2S8+WiH0o=
  template:
    metadata:
      name: hcloud
      namespace: kube-system
    type: Opaque
