apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: penpot
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.penpot.app/
      chart: penpot
      targetRevision: 0.40.0
      helm:
        releaseName: penpot
        values: |
          global:
            postgresqlEnabled: true
            valkeyEnabled: true

          config:
            publicUri: https://penpot.k6nis.dev
            flags: enable-registration enable-login-with-password disable-email-verification
            apiSecretKey: YwHCmN_oOtS1wRRxwKD2lML8up32J6Am3iCFTkRaBHoPEkyfgb58vjKJyIOJ2rQyRmUwYns96YpzObjHOFluLg
            telemetryEnabled: false

          persistence:
            assets:
              enabled: true
              size: 20Gi

          postgresql:
            auth:
              postgresPassword: penpot

          ingress:
            enabled: false
    - repoURL: https://github.com/kubeden/kubeden.git
      targetRevision: main
      path: k8s-cluster-configuration/applications/penpot/base
  destination:
    server: https://kubernetes.default.svc
    namespace: penpot
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
